// SPDX-License-Identifier: EUPL-1.2
const js = require('@eslint/js');
const globals = require('globals');

module.exports = [
    {
        ignores: [
            '.claude/**',
            '.Codex/**',
            '.analysis-*/**',
            '.pipeline-artifacts/**',
            '.qa-test-results/**',
            'coverage*/**',
            '**/bin/**',
            '**/obj/**',
            '**/node_modules/**',
            'site/**',
            'src/Aetheus.Front/wwwroot/lib/**',
            // Generated by docs-site/src/build.mjs from docs-site/src, which is linted instead.
            'docs-site/public/**',
            // Deliberately vulnerable targets of the OpenGrep rule tests (opengrep --test).
            'tests/security-rules/**'
        ]
    },
    js.configs.recommended,
    {
        files: ['src/Aetheus.Front/wwwroot/js/**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                ...globals.browser,
                Aetheus: 'writable',
                dagre: 'readonly',
                monaco: 'readonly',
                require: 'readonly'
            }
        },
        rules: {
            complexity: ['warn', 10],
            'no-eval': 'error',
            'no-implied-eval': 'error',
            'no-unused-vars': ['error', { argsIgnorePattern: '^_' }]
        }
    },
    {
        files: [
            'src/Aetheus.Front/wwwroot/js/dockerGraph.js',
            'src/Aetheus.Front/wwwroot/js/aetheus-analytics-bootstrap.js',
            'src/Aetheus.Front/wwwroot/js/omni-code-editor-frame.js',
            'src/Aetheus.Front/wwwroot/js/omni-monaco-frame.js'
        ],
        languageOptions: { sourceType: 'module' }
    },
    {
        files: ['src/Aetheus.Front/wwwroot/service-worker.js'],
        languageOptions: { sourceType: 'script', globals: globals.serviceworker }
    },
    {
        files: ['docs-site/src/assets/js/**/*.js'],
        languageOptions: { sourceType: 'script', globals: globals.browser }
    },
    {
        files: [
            'deploy/scripts/**/*.mjs',
            'docs-site/src/**/*.mjs',
            'docs/tools/**/*.mjs',
            'tests/js/**/*.mjs',
            'packages/aetheus-web-analytics/test/**/*.js'
        ],
        rules: {
            // Rest destructuring that drops a property on purpose is not an unused variable.
            'no-unused-vars': ['error', { ignoreRestSiblings: true }]
        },
        languageOptions: {
            sourceType: 'module',
            globals: {
                ...globals.node,
                ...globals.browser
            }
        }
    },
    {
        files: ['packages/aetheus-web-analytics/src/**/*.js'],
        languageOptions: {
            sourceType: 'module',
            globals: globals.browser
        }
    },
    {
        files: ['tests/js/**/*.cjs'],
        languageOptions: {
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                ...globals.browser,
                Aetheus: 'writable'
            }
        }
    }
];
