// SPDX-License-Identifier: EUPL-1.2
namespace Aetheus.Agent.Core.Configuration;

public sealed class AetheusAgentOptions
{
    public const string SectionName = "Aetheus";

    public string ServerUrl { get; set; } = Aetheus.Shared.Components.Shared.LocalDevelopmentEndpoints.ApiHttpsBaseUrl;
    public string? Name { get; set; }
    public int PollingIntervalSeconds { get; set; } = AgentRuntimeDefaults.PollingIntervalSeconds;
    public int HeartbeatIntervalSeconds { get; set; } = AgentRuntimeDefaults.HeartbeatIntervalSeconds;
    /// <summary>
    /// Maximum time spent waiting for inventory collectors before sending a degraded heartbeat.
    /// Keeps Docker or OS probes from making a healthy task poller appear offline.
    /// </summary>
    public int HeartbeatCollectionTimeoutSeconds { get; set; } = AgentRuntimeDefaults.HeartbeatCollectionTimeoutSeconds;
    public int MaxConcurrentTasks { get; set; } = AgentRuntimeDefaults.MaximumConcurrentTasks;
    public string WorkDirectory { get; set; } = Path.Combine(AppContext.BaseDirectory, "data");
    public string PluginDirectory { get; set; } = Path.Combine(AppContext.BaseDirectory, "plugins");
    public int LogRetentionDays { get; set; } = AgentRuntimeDefaults.LogRetentionDays;
    public bool AllowInsecureCerts { get; set; }

    /// <summary>S-FEAT-24: SHA-256 thumbprint (hex) of the backend's TLS certificate. When set, the
    /// agent accepts the server cert only if its thumbprint matches - pinning the self-signed dev cert
    /// without disabling validation for every cert (unlike <see cref="AllowInsecureCerts"/>). Takes
    /// precedence over AllowInsecureCerts.</summary>
    public string? PinnedServerCertThumbprint { get; set; }

    public int MinTimeoutSeconds { get; set; } = AgentRuntimeDefaults.MinimumTaskTimeoutSeconds;
    public int MaxTimeoutSeconds { get; set; } = AgentRuntimeDefaults.MaximumTaskTimeoutSeconds;

    // DEPV: deploy tuning, previously hard-coded in DeployLayout. An operator on a disk-constrained
    // box or with large self-contained artifacts can adjust these via the agent config section.
    /// <summary>Recent release dirs kept per app after a successful deploy (the rest are pruned).</summary>
    public int DeployReleasesToKeep { get; set; } = AgentRuntimeDefaults.DeployReleasesToKeep;
    /// <summary>Free-space floor (MiB) required on top of the unpacked-payload estimate before extracting.</summary>
    public int DeployMinFreeSpaceMiB { get; set; } = AgentRuntimeDefaults.DeployMinimumFreeSpaceMiB;
    /// <summary>Heuristic unpacked-to-compressed ratio used for the free-space estimate (publish trees ~2–3×).</summary>
    public int DeployUnpackRatioEstimate { get; set; } = AgentRuntimeDefaults.DeployUnpackRatioEstimate;
    public DockerStorageMaintenanceOptions DockerStorageMaintenance { get; set; } = new();
    public List<string> AllowedCommandPatterns { get; set; } =
    [
        @"^dotnet\s",
        @"^git\s",
        @"^docker\s",
        @"^npm\s",
        @"^node\s",
        @"^python3?\s",
        @"^pip3?\s",
        @"^systemctl\s+(status|restart|start|stop)\s",
        @"^journalctl\s",
        @"^cp\s",
        @"^mv\s",
        @"^mkdir\s",
        @"^ls\s",
        @"^cat\s+[a-zA-Z0-9_./ -]+$",
        @"^echo\s",
        @"^curl\s+-[sfSLo]+\s",
        @"^wget\s+-[qO]+\s",
        @"^chmod\s+[0-7]{3}\s",
        @"^chown\s",
        @"^tar\s",
        @"^unzip\s",
        // Index refresh / upgrade of already-installed packages - these never pull an arbitrary new
        // package, so they stay general.
        @"^apt(-get)?\s+(update|upgrade)(\s|$)",
        // Install/remove is restricted to the managed-service catalogue (defence-in-depth: the backend
        // already validates the service name against WellKnownManageableServices - this is the agent-
        // side guardrail so a task can NOT apt-install an arbitrary package). Matches exactly what
        // ServerService.InstallServiceAsync/UninstallServiceAsync emit. KEEP THIS LIST IN LOCKSTEP with
        // WellKnownManageableServices in src/Aetheus.Back/Components/Servers/ServerService.cs.
        @"^apt-get\s+install\s+-y\s+(nginx|apache2|docker|fail2ban|rkhunter|ufw|portsentry|postfix|dovecot|mysql|mariadb|postgresql|redis-server|mongod)$",
        @"^apt-get\s+remove\s+-y\s+(nginx|apache2|docker|fail2ban|rkhunter|ufw|portsentry|postfix|dovecot|mysql|mariadb|postgresql|redis-server|mongod)$",
        @"^yum\s+(install|update)\s",
        @"^rkhunter\s+--check\s+--skip-keypress\s+--nocolors$",
        @"^rkhunter\s+--update\s+--nocolors$",
        @"^rkhunter\s+--propupd\s+--nocolors$",
        // RKHunter setup chain (joined by `&&`) + log tail - each is one metacharacter-free
        // segment generated by RkhunterCommandHelper. Keep these in lockstep with that helper.
        @"^export\s+DEBIAN_FRONTEND=noninteractive$",
        @"^apt-get\s+update\s+-qq$",
        @"^apt-get\s+install\s+-y\s+-qq\s+rkhunter$",
        @"^sed\s+-i\s+'s/.*MAIL-ON-WARNING.*/'\s+/etc/rkhunter\.conf$",
        @"^tail\s+-n\s+\d+\s+/var/log/rkhunter\.log$",
        @"^Get-",
        @"^Set-(Content|Location|Item|ItemProperty)\s",
        @"^New-",
        @"^Remove-(Item)\s",
        @"^Start-(Process|Service)\s",
        @"^Stop-(Process|Service)\s",
        @"^Restart-(Service)\s",
        @"^Copy-Item\s",
        @"^Move-Item\s",
        @"^Test-Path\s"
    ];
}
