<Project Sdk="Microsoft.NET.Sdk">



  <ItemGroup>
    <InternalsVisibleTo Include="Aetheus.Agent.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\scanner-manifest.json" Link="scanner-manifest.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aetheus.Analyzers\Aetheus.Analyzers.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
