<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <EnableAetheusTelemetry Condition="'$(EnableAetheusTelemetry)' == ''">false</EnableAetheusTelemetry>
    <EnableAetheusWebAnalytics Condition="'$(EnableAetheusWebAnalytics)' == ''">false</EnableAetheusWebAnalytics>
    <AetheusTelemetryVersion Condition="'$(AetheusTelemetryVersion)' == ''">0.1.0</AetheusTelemetryVersion>
    <AetheusWebAnalyticsVersion Condition="'$(AetheusWebAnalyticsVersion)' == ''">0.1.0</AetheusWebAnalyticsVersion>
    <DefineConstants Condition="'$(EnableAetheusTelemetry)' == 'true'">$(DefineConstants);AETHEUS_TELEMETRY</DefineConstants>
    <DefineConstants Condition="'$(EnableAetheusWebAnalytics)' == 'true'">$(DefineConstants);AETHEUS_WEB_ANALYTICS</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(EnableAetheusTelemetry)' == 'true'">
    <PackageReference Include="Aetheus.Telemetry" Version="$(AetheusTelemetryVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(EnableAetheusWebAnalytics)' == 'true'">
    <PackageReference Include="Aetheus.WebAnalytics" Version="$(AetheusWebAnalyticsVersion)" />
  </ItemGroup>

</Project>
