// SPDX-License-Identifier: EUPL-1.2
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using Aetheus.Back;
using Aetheus.Back.Components.Auth;
using Aetheus.Back.Components.Git;
using Aetheus.Back.Components.PackageRegistry;
using Aetheus.Back.Components.PersonalAccessTokens;
using Aetheus.Back.Configuration;
using Aetheus.Back.Extensions;
using Aetheus.Back.Hubs;
using Aetheus.Back.Middleware;
using Aetheus.Telemetry;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

// --- File logging (JSON) ---
var logDirectory = builder.Configuration["Logging:FileLog:Directory"]
    ?? Path.Combine(AppContext.BaseDirectory, "logs");
Directory.CreateDirectory(logDirectory);
// The JSON file sink writes synchronously under a single lock, so its level
// drives throughput under load. It does NOT bind appsettings "Logging" - set it
// explicitly: Warning in Production (steady-state ≈ silent, no per-request disk
// I/O contention), Information in dev. Override via Logging:FileLog:MinLevel.
var fileLogLevel = Enum.TryParse<LogLevel>(
    builder.Configuration["Logging:FileLog:MinLevel"], ignoreCase: true, out var lvl)
        ? lvl
        : builder.Environment.IsProduction() ? LogLevel.Warning : LogLevel.Information;
builder.Logging.AddProvider(new JsonFileLoggerProvider(logDirectory, fileLogLevel));

// Self-observability is deployment-controlled and remains disabled when the injected
// AETHEUS_TELEMETRY_ENABLED variable is absent. Production deploy stages receive a
// short-lived ingest key from the monitored application selected for this project.
builder.Services.AddAetheusTelemetry(builder.Configuration, options =>
{
    options.ApplicationVersion = builder.Configuration["App:Version"];
    options.EnvironmentName = builder.Environment.EnvironmentName.ToLowerInvariant();
});

// --- Time ---
builder.Services.AddSingleton(TimeProvider.System);
// Recette R-457: RequestErrorLoggingMiddleware counts the refused requests that match no route.
builder.Services.AddSingleton<UnmatchedRequestCounter>();

// --- Data Protection ---
// Persist keys to a known directory so cookie/token protectors survive container
// restarts. Encrypt keys at rest with a self-signed certificate generated by
// the entrypoint script (silences "No XML encryptor configured" warning).
var dpKeyPath = builder.Configuration["DataProtection:KeyPath"]
    ?? (builder.Environment.IsDevelopment()
        ? Path.Combine(AppContext.BaseDirectory, "dp-keys")
        : "/app/data/dp-keys");
Directory.CreateDirectory(dpKeyPath);
var dpBuilder = builder.Services.AddDataProtection()
    .PersistKeysToFileSystem(new DirectoryInfo(dpKeyPath))
    .SetApplicationName("Aetheus");
var dpCertPath = Path.Combine(dpKeyPath, "dp-cert.pfx");
if (File.Exists(dpCertPath))
{
    var dpCert = X509CertificateLoader.LoadPkcs12FromFile(dpCertPath, password: null);
    dpBuilder.ProtectKeysWithCertificate(dpCert);
}

// --- Database (PostgreSQL only) ---
var connectionString = builder.Configuration.GetConnectionString("Default");
if (string.IsNullOrWhiteSpace(connectionString))
{
    throw new InvalidOperationException(
        "ConnectionStrings:Default is not configured. Aetheus requires a PostgreSQL connection string. " +
        "For local development, run the dev database via 'docker compose -f deploy/compose/dev-db.compose.yml up -d' " +
        "and set ConnectionStrings:Default in appsettings.Development.json or via environment variable.");
}
// The E2E schema reset (/api/dev/reset-db, Development only) closes this gate; the interceptor that
// holds the other commands back while it is closed is only added in Development.
builder.Services.AddSingleton<Aetheus.Back.Components.Dev.SchemaResetGate>();
builder.Services.AddSingleton<Aetheus.Back.Components.Dev.SchemaResetInterceptor>();
var addSchemaResetInterceptor = builder.Environment.IsDevelopment();
builder.Services.AddDbContext<AppDbContext>((services, options) =>
{
    if (addSchemaResetInterceptor)
        options.AddInterceptors(services.GetRequiredService<Aetheus.Back.Components.Dev.SchemaResetInterceptor>());
    options.UseNpgsql(connectionString)
        .ConfigureWarnings(w => w.Ignore(
            Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning,
            // PLAN-004 R-11: the retired-server filter sits on the required end of ~40 relationships
            // (metrics, tasks, project-servers...). EF warns that such dependents vanish from joins with
            // their filtered principal; for a retired server that is exactly the intended behaviour,
            // and the paths that must still see those rows opt out with ServerQueryFilters.ExcludeRetired.
            Microsoft.EntityFrameworkCore.Diagnostics.CoreEventId.PossibleIncorrectRequiredNavigationWithQueryFilterInteractionWarning));
});

// --- Authentication ---
// F-37: bind strongly typed options for the Auth section (consumers can inject IOptions<T>).
builder.Services.Configure<Aetheus.Back.Configuration.AuthOptions>(
    builder.Configuration.GetSection(Aetheus.Back.Configuration.AuthOptions.SectionName));
builder.Services.Configure<Aetheus.Back.Configuration.AgentTokenOptions>(
    builder.Configuration.GetSection(Aetheus.Back.Configuration.AgentTokenOptions.SectionName));
builder.Services.Configure<Aetheus.Back.Configuration.EncryptionOptions>(
    builder.Configuration.GetSection(Aetheus.Back.Configuration.EncryptionOptions.SectionName));

var jwtKey = builder.Configuration["Auth:JwtKey"];
if (string.IsNullOrEmpty(jwtKey))
{
    if (!builder.Environment.IsDevelopment())
        throw new InvalidOperationException("Auth:JwtKey must be configured in non-development environments.");
    // Generate a per-process random key in Development when Auth:JwtKey is unset.
    // Tokens are invalidated on restart - set Auth:JwtKey for stable dev sessions.
    jwtKey = Convert.ToBase64String(RandomNumberGenerator.GetBytes(48));
    // #60: warn so devs understand why "Remember me" stops working after each restart.
    Console.WriteLine(
        "[WARN] Auth:JwtKey is not set. Generated an ephemeral signing key for this process; " +
        "all issued JWTs (including Remember Me sessions) will be invalidated on restart. " +
        "Configure Auth:JwtKey in appsettings.Development.json or user-secrets to persist sessions.");
}

// F-01: Refuse to run with publicly known default secrets in non-Development environments.
// These literals were committed in earlier appsettings.json revisions and are therefore burned.
if (!builder.Environment.IsDevelopment())
{
    var knownDefaultJwtKeys = new[] { "aetheus-dev-key-minimum-32-bytes!!" };
    var knownDefaultEncKeys = new[] { "aetheus-encryption-key-32ch!" };
    if (Array.Exists(knownDefaultJwtKeys, k => string.Equals(k, jwtKey, StringComparison.Ordinal)))
        throw new InvalidOperationException(
            "Auth:JwtKey is set to a publicly known default value. Rotate the signing key before starting in non-development environments.");

    var encKey = builder.Configuration["Auth:EncryptionKey"];
    if (!string.IsNullOrEmpty(encKey)
        && Array.Exists(knownDefaultEncKeys, k => string.Equals(k, encKey, StringComparison.Ordinal)))
        throw new InvalidOperationException(
            "Auth:EncryptionKey is set to a publicly known default value. Rotate the encryption key before starting in non-development environments.");

    if (string.IsNullOrEmpty(encKey))
        throw new InvalidOperationException(
            "Auth:EncryptionKey must be configured in non-development environments (set via the Auth__EncryptionKey environment variable).");

    var encSalt = builder.Configuration["Auth:EncryptionSalt"];
    if (string.IsNullOrEmpty(encSalt))
        throw new InvalidOperationException(
            "Auth:EncryptionSalt must be configured in non-development environments (set via the Auth__EncryptionSalt environment variable, base64, >= 16 bytes).");

    var adminPwd = builder.Configuration["Auth:AdminPassword"];
    if (string.Equals(adminPwd, "admin", StringComparison.OrdinalIgnoreCase))
        throw new InvalidOperationException(
            "Auth:AdminPassword must not be the default 'admin' value in non-development environments.");
}
// Single, validated source of truth for JWT signing - services must inject JwtOptions and never
// re-resolve Auth:JwtKey from configuration.
var jwtOptions = new JwtOptions { SigningKey = jwtKey };
builder.Services.AddSingleton(jwtOptions);

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwtOptions.Issuer,
            ValidAudience = jwtOptions.Audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
            ClockSkew = BackendRuntimeDefaults.JwtClockSkew
        };

        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                // Allow SignalR to receive token from query string (only for /hubs paths).
                // Browser WebSocket clients cannot set Authorization headers, so SignalR passes
                // the JWT as the `access_token` query param - standard and unavoidable.
                // LOG-HYGIENE INVARIANT: this token must never reach the logs. ASP.NET Core's
                // `Microsoft.AspNetCore.Hosting.Diagnostics` emits a "Request starting ... ?query"
                // line (which would include access_token) at Information level. Both appsettings
                // pin `Microsoft.AspNetCore` to `Warning`, suppressing that line in every sink
                // (console + the JSON file logger). Do NOT lower that category to Information
                // without first redacting the access_token query param, or tokens will be logged.
                var accessToken = context.Request.Query["access_token"];
                var path = context.HttpContext.Request.Path;
                if (!string.IsNullOrEmpty(accessToken) && path.StartsWithSegments("/hubs"))
                {
                    context.Token = accessToken;
                }
                return Task.CompletedTask;
            },
            OnTokenValidated = async context =>
            {
                // Immediate revocation: reject tokens whose SecurityStamp claim no longer matches
                // the user's current persisted stamp (bumped on password / role change / logout).
                var principal = context.Principal;
                if (principal is null) return;

                var nameIdClaim = principal.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
                var stampClaim = principal.FindFirst(AetheusClaimTypes.SecurityStamp);

                if (nameIdClaim is null || string.IsNullOrWhiteSpace(nameIdClaim.Value)
                    || stampClaim is null || string.IsNullOrWhiteSpace(stampClaim.Value))
                {
                    context.Fail("Token is missing mandatory revocation claims.");
                    return;
                }

                // Hardening (#19): bootstrap admin tokens are now revocable too - they carry
                // a deterministic NameIdentifier="bootstrap" + SecurityStamp="bootstrap". The
                // operator can rotate this stamp via Auth:BootstrapStamp config, instantly
                // invalidating outstanding bootstrap tokens.
                if (nameIdClaim.Value == "bootstrap")
                {
                    var cfg = context.HttpContext.RequestServices.GetRequiredService<IConfiguration>();
                    var currentStamp = cfg["Auth:BootstrapStamp"] ?? "bootstrap";
                    if (!CryptographicOperations.FixedTimeEquals(
                            Encoding.UTF8.GetBytes(stampClaim.Value),
                            Encoding.UTF8.GetBytes(currentStamp)))
                        context.Fail("Bootstrap token security stamp is no longer valid.");
                    return;
                }

                if (!int.TryParse(nameIdClaim.Value, out var userId))
                {
                    context.Fail("Token subject is invalid.");
                    return;
                }

                var auth = context.HttpContext.RequestServices.GetRequiredService<IAuthService>();
                if (!await auth.IsSecurityStampValidAsync(userId, stampClaim.Value, context.HttpContext.RequestAborted))
                    context.Fail("Token security stamp is no longer valid.");
            }
        };

        // JWT is the default Bearer scheme. Forward PAT-shaped tokens and endpoints explicitly
        // protected by the AgentToken policy before the global rate limiter evaluates the principal.
        options.ForwardDefaultSelector = BearerAuthenticationSchemeSelector.Resolve;
    })
    .AddScheme<AuthenticationSchemeOptions, AgentTokenAuthenticationHandler>(
        AgentTokenAuthenticationHandler.SchemeName, _ => { })
    .AddScheme<AuthenticationSchemeOptions, GitBasicAuthenticationHandler>(
        GitBasicAuthenticationHandler.SchemeName, _ => { })
    .AddScheme<AuthenticationSchemeOptions, PatAuthenticationHandler>(
        PatAuthenticationHandler.SchemeName, _ => { })
    .AddScheme<AuthenticationSchemeOptions, PackageRegistryAuthenticationHandler>(
        PackageRegistryAuthenticationHandler.SchemeName, _ => { });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AgentToken", policy =>
        policy.AddAuthenticationSchemes(AgentTokenAuthenticationHandler.SchemeName)
              .RequireRole("Agent"));
});

// --- Services (Vertical Slice DI) ---
builder.Services.AddAetheusModules(builder.Configuration);

// --- Shared Services ---
builder.Services.AddHttpContextAccessor();
builder.Services.AddHttpClient();
builder.Services.AddSingleton<IEncryptionService, EncryptionService>();
builder.Services.AddScoped<ISecretMaskingRepository, SecretMaskingRepository>();
builder.Services.AddScoped<ISecretMaskingService, SecretMaskingService>();
builder.Services.AddScoped<IPermissionRepository, PermissionRepository>();
builder.Services.AddSingleton<AuthzCacheEvictor>();
builder.Services.AddScoped<IResourceAuthorizationService, ResourceAuthorizationService>();
builder.Services.AddSingleton<IEntityChangeNotifier, EntityChangeNotifier>();
builder.Services.AddSingleton<IAdminChangeNotifier, AdminChangeNotifier>();
builder.Services.AddSingleton<IUserChangeNotifier, UserChangeNotifier>();
builder.Services.AddScoped<IGitCliService, GitCliService>();
builder.Services.AddScoped<IDbTransactionScope, DbTransactionScope>();

// Background services configuration (timeouts, intervals).
builder.Services.Configure<BackgroundServicesOptions>(
    builder.Configuration.GetSection("BackgroundServices"));

// --- Caching ---
builder.Services.AddMemoryCache();

// --- Request body size limit (F-024) ---
// Cap request bodies at 10 MB to bound memory / DoS exposure. Endpoints needing
// larger payloads can override per-action with [RequestSizeLimit]/[DisableRequestSizeLimit].
builder.Services.Configure<Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions>(
    o => o.Limits.MaxRequestBodySize = 10_485_760);

// --- SignalR ---
builder.Services.AddSignalR();

// --- Controllers ---
builder.Services.AddControllers(options =>
{
    options.Filters.Add(new Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute(StatusCodes.Status401Unauthorized));
    options.Filters.Add(new Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute(StatusCodes.Status403Forbidden));
}).AddJsonOptions(json =>
{
    json.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
});
builder.Services.AddScoped<LoginValidationAuditFilter>();

// Surface validation failures in the server logs so heartbeat / telemetry endpoints don't
// fail silently with a generic 400 response - the agent only sees the status code by default.
builder.Services.Configure<Microsoft.AspNetCore.Mvc.ApiBehaviorOptions>(options =>
{
    var defaultFactory = options.InvalidModelStateResponseFactory;
    options.InvalidModelStateResponseFactory = ctx =>
    {
        var logger = ctx.HttpContext.RequestServices
            .GetRequiredService<ILoggerFactory>()
            .CreateLogger("ModelValidation");
        var errors = ctx.ModelState
            .Where(kv => kv.Value?.Errors.Count > 0)
            .Select(kv => $"{kv.Key}: {string.Join("; ", kv.Value!.Errors.Select(e => e.ErrorMessage))}");
        logger.LogWarning("400 ModelState invalid on {Method} {Path}: {Errors}",
            ctx.HttpContext.Request.Method,
            ctx.HttpContext.Request.Path,
            string.Join(" | ", errors));
        return defaultFactory(ctx);
    };
});

// --- Response compression ---
builder.Services.AddResponseCompression(options =>
{
    options.EnableForHttps = false;
    // F-015 (BREACH): application/json is explicitly excluded - in production Apache terminates
    // TLS and proxies plain HTTP to Kestrel, so EnableForHttps=false alone does not prevent
    // compressed JSON (which can reflect secrets) from being served over HTTPS.
    options.MimeTypes = ResponseCompressionDefaults.MimeTypes
        .Concat(["text/plain"])
        .Where(m => !m.Contains("json", StringComparison.OrdinalIgnoreCase));
});

// --- API versioning (F-27) ---
// Default version v1.0 is assumed when callers omit the version. Negotiation strategy
// favours opt-in headers/query so existing clients continue to work without URL changes.
builder.Services.AddApiVersioning(options =>
{
    options.DefaultApiVersion = new Asp.Versioning.ApiVersion(1, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.ReportApiVersions = true;
    options.ApiVersionReader = Asp.Versioning.ApiVersionReader.Combine(
        new Asp.Versioning.HeaderApiVersionReader("X-Api-Version"),
        new Asp.Versioning.QueryStringApiVersionReader("api-version"));
}).AddMvc();

// --- CORS ---
var corsOrigins = new List<string>();
if (builder.Environment.IsDevelopment())
{
    corsOrigins.Add(LocalDevelopmentEndpoints.FrontendHttpsOrigin);
    corsOrigins.Add(LocalDevelopmentEndpoints.FrontendHttpOrigin);
}
var frontendUrl = builder.Configuration["Cors:FrontendUrl"];
if (!string.IsNullOrEmpty(frontendUrl))
    corsOrigins.Add(frontendUrl);
var originsSection = builder.Configuration.GetSection("Cors:Origins");
if (originsSection.Exists())
    foreach (var origin in originsSection.GetChildren())
        if (!string.IsNullOrEmpty(origin.Value))
            corsOrigins.Add(origin.Value);
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.WithOrigins(corsOrigins.Distinct().ToArray())
            .WithHeaders("Authorization", "Content-Type", "X-Api-Version", "X-Requested-With", "x-signalr-user-agent", "x-requested-with", "X-Aetheus-Renewal")
            .WithMethods("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
            .WithExposedHeaders(RequestErrorLoggingMiddleware.CorrelationHeader)
            .AllowCredentials()
            .SetPreflightMaxAge(BackendRuntimeDefaults.CorsPreflightMaxAge);
    });
});

builder.Services.AddAetheusRateLimiting(builder.Configuration);

// --- OpenAPI ---
builder.Services.AddOpenApi();
for (var partition = 0; partition < OpenApiDastPartition.Count; partition++)
{
    var currentPartition = partition;
    builder.Services.AddOpenApi(
        OpenApiDastPartition.DocumentName(currentPartition),
        options => options.ShouldInclude = description =>
            OpenApiDastPartition.Includes(description, currentPartition));
}

// --- Health Checks ---
builder.Services.AddHealthChecks()
    .AddDbContextCheck<AppDbContext>("database");

var app = builder.Build();

// S-TECH-RTKP: the pipeline clone token (GitRunCloneToken) prefers a dedicated GitLight:RunTokenKey and
// falls back to the AES Auth:EncryptionKey (HKDF domain-separated, so safe). In production a dedicated
// key is cleaner: warn (don't fail) when it is absent so the operator can provision one.
if (app.Environment.IsProduction() && string.IsNullOrEmpty(app.Configuration["GitLight:RunTokenKey"]))
    app.Logger.LogWarning(
        "GitLight:RunTokenKey is not configured; pipeline clone tokens fall back to the HKDF-derived " +
        "Auth:EncryptionKey. Set GitLight__RunTokenKey to a dedicated secret for clearer key separation.");

// --- Database initialization ---
await using (var scope = app.Services.CreateAsyncScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var startupLogger = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("Startup");
    // MigrateAsync is relational-only; tests swap the provider to InMemory and would throw.
    if (db.Database.IsRelational())
    {
        // S-TECH-58: guard against a parasitic instance (e.g. a second checkout/worktree pointed at
        // the shared dev DB) applying divergent migrations. Setting Database:SkipMigrations=true (or
        // AETHEUS_SKIP_MIGRATIONS=1) makes the instance attach read/write WITHOUT migrating - the
        // canonical instance owns the schema. Defaults to migrating, so prod startup is unchanged.
        var skipMigrations = app.Configuration.GetValue("Database:SkipMigrations", false)
            || string.Equals(Environment.GetEnvironmentVariable("AETHEUS_SKIP_MIGRATIONS"), "1", StringComparison.Ordinal);
        if (skipMigrations)
        {
            // R-464: expected on both blue-green colours, whose schema the migration-only job applies
            // before they start; the former "Unset this flag on the primary node" wrongly read as a fault.
            startupLogger.LogInformation(
                "Database:SkipMigrations is set: this instance does not apply EF migrations. The schema is " +
                "migrated by its owner (the blue-green migration job, or the canonical development instance).");
        }
        else
        {
            startupLogger.LogInformation("Applying EF migrations to database '{Database}'", db.Database.GetDbConnection().Database);
            await db.Database.MigrateAsync();
        }
    }

    await DbInitializer.SeedAsync(db, app.Configuration);
    await scope.ServiceProvider.GetRequiredService<TotoConformanceSeeder>().SeedAsync();
    await DemoDataStartupSeeder.SeedIfEnabledAsync(scope.ServiceProvider, db, app.Environment, app.Configuration);
    // Reconcile the canonical catalog last: optional demo seeders must not be able to
    // recreate active non-canonical templates after the legacy archival pass.
    await scope.ServiceProvider.GetRequiredService<DeliveryPipelineTemplateSeeder>().SeedAsync();

    // PLAN-005 lot 6: carries the two port fields that predate the registry into it. Idempotent, and
    // non-destructive - a port already held by somebody else is left to its holder and reported.
    await Aetheus.Back.Components.PortRegistry.IsolatedPortBackfill.RunAsync(
        db,
        scope.ServiceProvider.GetRequiredService<Aetheus.Back.Components.PortRegistry.IPortRegistryService>(),
        startupLogger);

    // Audit 360 lot A: one-shot, idempotent re-encryption of any residual plaintext webhook secrets
    // written before secrets were encrypted at rest. Lets WebhookService decrypt strictly afterwards.
    var encryptionService = scope.ServiceProvider.GetRequiredService<Aetheus.Back.Services.IEncryptionService>();
    await Aetheus.Back.Components.Webhooks.WebhookSecretReencryption.RunAsync(db, encryptionService, startupLogger);
    await Aetheus.Back.Components.Notifications.NotificationConfigurationReencryption.RunAsync(
        db, encryptionService, startupLogger);
}

// --- Middleware ---
// Behind the Apache reverse proxy (a loopback hop on the same host), restore the client's original
// scheme/IP from the X-Forwarded-* headers BEFORE anything downstream reads Request.Scheme/Request.Host
// - otherwise email links, OAuth redirects, 201 Location headers, and AgentInstaller URLs all emit
// http:// instead of https://. Must run first, ahead of HSTS/security-headers/auth.
//
// The defaults accept forwarded headers only from loopback, and the previous claim that this "is
// exactly the Apache hop here" holds solely when the backend runs directly on the host. In
// production it runs in a container, so Apache reaches it through the Docker bridge gateway, never
// 127.0.0.1: the defaults silently DROPPED X-Forwarded-Proto and every absolute URL came out as
// http://. That is what made `dotnet nuget push` read an http:// publish endpoint from the v3 index
// and refuse to publish, because NuGet requires HTTPS sources.
//
// Clearing both lists is safe HERE and only here: Compose binds the backend to 127.0.0.1:<port> on
// the host, so nothing but the local Apache vhost can open a connection to it, and that vhost sets
// X-Forwarded-Proto itself. If the port is ever published on a public interface these headers become
// spoofable and this must be revisited.
var forwardedHeadersOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
};
forwardedHeadersOptions.KnownIPNetworks.Clear();
forwardedHeadersOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeadersOptions);

// The public application and Git smart-HTTP endpoint are HTTPS-only in production. Forwarded
// headers above make this work correctly behind Apache; local development deliberately keeps its
// HTTP listener for the agent and test topology. R-464: the middleware runs only where it can find an
// HTTPS port; in the production container (HTTP behind Apache's TLS) it redirected nothing and logged
// "Failed to determine the https port for redirect" on every plain request. The public HTTP to HTTPS
// redirect is Apache's.
if (!app.Environment.IsDevelopment() && HttpsPortConfiguration.IsKnown(app.Configuration))
    app.UseHttpsRedirection();

// S-FEAT-27: serve the OpenAPI spec in every environment so the in-app API Reference page can render
// it. In Development it stays anonymous (tooling/Scalar); elsewhere it is gated to administrators only
// - the in-app API Reference is an admin surface, so the spec must not be readable by any authenticated
// user (matching the nav, which already hides the page from non-admins).
if (app.Environment.IsDevelopment())
    app.MapOpenApi();
else
{
    app.MapOpenApi().RequireAuthorization(new AuthorizeAttribute { Roles = "Admin" });
    // F-26: enable HSTS in non-Development environments.
    app.UseHsts();
}

app.UseAetheusSecurityHeaders(corsOrigins);
app.UseMiddleware<RequestErrorLoggingMiddleware>();
app.UseMiddleware<ErrorHandlingMiddleware>();
app.UseResponseCompression();
// The public analytics endpoint validates its per-application origin against the database and
// emits its own narrow CORS headers. The global static policy must not short-circuit its preflight.
app.UseWhen(
    context => !context.Request.Path.StartsWithSegments(
        "/api/ingest/web-analytics/v1/public",
        StringComparison.OrdinalIgnoreCase),
    branch => branch.UseCors());
// UseRateLimiter MUST run after UseAuthentication so the GlobalLimiter sees a populated HttpContext.User
// (F-24): its per-user partition key reads User.Identity.IsAuthenticated, which is still false before
// authentication runs, collapsing every authenticated caller onto a shared per-IP bucket.
app.UseAuthentication();
app.UseRateLimiter();
app.UseAuthorization();
// Read-only Personal Access Token enforcement (ADR-024 4.5): runs after authorization so
// HttpContext.User carries the PAT principal; refuses mutating requests made with a read-only PAT.
app.UseMiddleware<PatScopeEnforcementMiddleware>();

// --- Agent server URL (used by AddAgent wizard) ---
app.MapGet("/api/servers/agent-server-url", (IConfiguration config, HttpContext httpContext) =>
    Results.Ok(new { Url = HostUrlExtensions.ResolvePublicApiUrl(config, httpContext) })
).RequireAuthorization();

// --- Agent binaries download (anonymous static files) ---
app.MapAgentDownloads();

// --- Endpoints ---
app.MapControllers();
app.MapHub<LogHub>("/hubs/logs");
app.MapHub<ServerHub>("/hubs/servers");
app.MapHub<PipelineHub>("/hubs/pipelines");
app.MapHub<ReleaseHub>("/hubs/releases");
app.MapHub<AlertHub>("/hubs/alerts");
app.MapHub<GitRealtimeHub>("/hubs/git");
app.MapHub<EntityHub>("/hubs/entities");
app.MapHub<AdminHub>("/hubs/admin");
app.MapHub<UserHub>("/hubs/user");
// F-18: /health (full checks incl. DB) requires authentication so unauthenticated callers
// can't probe service liveness. /health/live is an anonymous lightweight liveness probe
// for orchestrators / deploy scripts - it returns 200 as soon as the process is up.
app.MapHealthChecks("/health").RequireAuthorization();
app.MapHealthChecks("/health/live", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    Predicate = _ => false
}).AllowAnonymous();

// Readiness probe (challenge, blue-green): /health/live is process-up only, so a blue-green flip could cut
// over to a colour whose DB isn't connected yet. /health/ready runs the "database" check and returns 200
// only when the app can actually serve DB-backed requests. It exposes no details (status text only), so it
// is safe to expose anonymously - the same signal as "does this colour serve" that the deploy already gates on.
app.MapHealthChecks("/health/ready", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    Predicate = reg => reg.Name == "database"
}).AllowAnonymous();

app.Run();

public partial class Program { }
