// SPDX-License-Identifier: EUPL-1.2
using System.Collections.Frozen;
using OmniEurope.Blazor.Components;

namespace Aetheus.Front.Components.Shared;

/// <summary>
/// PLAN-008 lot 3: the Material icon names the front used before the migration, each with the Phosphor
/// <see cref="OmniIconName"/> that replaces it. Static names come from every <c>Icon="..."</c> of the
/// Razor sources, dynamic ones from the C# helpers and ternaries that computed an icon name. The
/// lot 14 wrappers keep their string <c>Icon</c> parameter through this table while pages still pass
/// Material names; the table goes with the wrappers at lot 34.
/// </summary>
public static class MaterialIconMap
{
    private static readonly FrozenDictionary<string, OmniIconName> Map = new Dictionary<string, OmniIconName>(StringComparer.Ordinal)
    {
        ["add"] = OmniIconName.Add,
        ["add_circle"] = OmniIconName.Add,
        ["add_link"] = OmniIconName.Link,
        ["admin_panel_settings"] = OmniIconName.ShieldCheck,
        ["alternate_email"] = OmniIconName.At,
        ["api"] = OmniIconName.PlugsConnected,
        ["approval"] = OmniIconName.Stamp,
        ["apartment"] = OmniIconName.Buildings,
        ["apps"] = OmniIconName.SquaresFour,
        ["arrow_back"] = OmniIconName.ArrowLeft,
        ["arrow_downward"] = OmniIconName.ArrowDown,
        ["arrow_forward"] = OmniIconName.ArrowRight,
        ["arrow_upward"] = OmniIconName.Upgrade,
        ["article"] = OmniIconName.Document,
        ["auto_awesome"] = OmniIconName.Sparkle,
        ["auto_delete"] = OmniIconName.Delete,
        ["auto_fix_high"] = OmniIconName.Sparkle,
        ["autorenew"] = OmniIconName.Sync,
        ["account_tree"] = OmniIconName.Graph,
        ["pipeline"] = OmniIconName.Graph,
        ["backup"] = OmniIconName.CloudArrowUp,
        ["bar_chart"] = OmniIconName.ChartBarHorizontal,
        ["block"] = OmniIconName.Prohibit,
        ["bolt"] = OmniIconName.Lightning,
        ["bug_report"] = OmniIconName.Bug,
        ["build"] = OmniIconName.Wrench,
        ["build_circle"] = OmniIconName.Wrench,
        ["call_merge"] = OmniIconName.GitMerge,
        ["call_split"] = OmniIconName.GitFork,
        ["campaign"] = OmniIconName.Megaphone,
        ["cancel"] = OmniIconName.Prohibit,
        ["cell_tower"] = OmniIconName.CellTower,
        ["center_focus_strong"] = OmniIconName.Target,
        ["check"] = OmniIconName.Check,
        ["check_circle"] = OmniIconName.CheckCircle,
        ["checklist"] = OmniIconName.ListChecks,
        ["chevron_right"] = OmniIconName.ChevronRight,
        ["cleaning_services"] = OmniIconName.Broom,
        ["clear"] = OmniIconName.Close,
        ["close"] = OmniIconName.Close,
        ["cloud"] = OmniIconName.Cloud,
        ["cloud_download"] = OmniIconName.CloudArrowDown,
        ["cloud_off"] = OmniIconName.Offline,
        ["cloud_upload"] = OmniIconName.CloudArrowUp,
        ["code"] = OmniIconName.Code,
        ["code_off"] = OmniIconName.EyeSlash,
        ["commit"] = OmniIconName.GitCommit,
        ["computer"] = OmniIconName.Monitor,
        ["construction"] = OmniIconName.Wrench,
        ["content_copy"] = OmniIconName.Copy,
        ["conversion_path"] = OmniIconName.Path,
        ["copy_all"] = OmniIconName.Copy,
        ["crisis_alert"] = OmniIconName.ShieldWarning,
        ["dark_mode"] = OmniIconName.ThemeDark,
        ["dashboard"] = OmniIconName.SquaresFour,
        ["data_object"] = OmniIconName.BracketsCurly,
        ["delete"] = OmniIconName.Delete,
        ["delete_forever"] = OmniIconName.Delete,
        ["delete_sweep"] = OmniIconName.Broom,
        ["deployed_code"] = OmniIconName.Package,
        ["description"] = OmniIconName.Document,
        ["difference"] = OmniIconName.GitDiff,
        ["dns"] = OmniIconName.Database,
        ["server"] = OmniIconName.Database,
        ["rzi-server"] = OmniIconName.Database,
        ["rzi-pipeline"] = OmniIconName.Graph,
        ["done_all"] = OmniIconName.Checks,
        ["download"] = OmniIconName.Download,
        ["drag_indicator"] = OmniIconName.DotsThreeVertical,
        ["drive_file_rename"] = OmniIconName.Edit,
        ["edit"] = OmniIconName.Edit,
        ["engineering"] = OmniIconName.Wrench,
        ["error"] = OmniIconName.Error,
        ["event"] = OmniIconName.CalendarBlank,
        ["event_available"] = OmniIconName.CalendarCheck,
        ["expand_less"] = OmniIconName.ChevronUp,
        ["expand_more"] = OmniIconName.ChevronDown,
        ["extension"] = OmniIconName.PuzzlePiece,
        ["fact_check"] = OmniIconName.ListChecks,
        ["fiber_new"] = OmniIconName.Sparkle,
        ["file_copy"] = OmniIconName.Copy,
        ["file_download"] = OmniIconName.Download,
        ["filter_list"] = OmniIconName.Filter,
        ["fit_screen"] = OmniIconName.FrameCorners,
        ["folder"] = OmniIconName.Folder,
        ["folder_open"] = OmniIconName.FolderOpen,
        ["folder_zip"] = OmniIconName.Archive,
        ["format_align_left"] = OmniIconName.TextAlignLeft,
        ["forum"] = OmniIconName.Chat,
        ["gavel"] = OmniIconName.Gavel,
        ["gpp_bad"] = OmniIconName.ShieldSlash,
        ["gpp_good"] = OmniIconName.ShieldCheck,
        ["gpp_maybe"] = OmniIconName.ShieldWarning,
        ["grade"] = OmniIconName.Medal,
        ["grid_view"] = OmniIconName.SquaresFour,
        ["group"] = OmniIconName.Users,
        ["group_add"] = OmniIconName.UserPlus,
        ["groups"] = OmniIconName.Users,
        ["hard_drive"] = OmniIconName.HardDrive,
        ["health_and_safety"] = OmniIconName.ShieldCheck,
        ["help"] = OmniIconName.Question,
        ["history"] = OmniIconName.Reset,
        ["home"] = OmniIconName.Home,
        ["hourglass_empty"] = OmniIconName.Hourglass,
        ["hourglass_top"] = OmniIconName.Hourglass,
        ["hub"] = OmniIconName.Graph,
        ["inbox"] = OmniIconName.Tray,
        ["info"] = OmniIconName.Info,
        ["insights"] = OmniIconName.ChartLineUp,
        ["install_desktop"] = OmniIconName.Monitor,
        ["inventory"] = OmniIconName.Package,
        ["inventory_2"] = OmniIconName.Archive,
        ["key"] = OmniIconName.Key,
        ["key_off"] = OmniIconName.LockOpen,
        ["label"] = OmniIconName.Tag,
        ["lan"] = OmniIconName.Graph,
        ["language"] = OmniIconName.Globe,
        ["layers"] = OmniIconName.Layers,
        ["library_books"] = OmniIconName.Books,
        ["light_mode"] = OmniIconName.ThemeLight,
        ["linear_scale"] = OmniIconName.Ruler,
        ["link"] = OmniIconName.Link,
        ["list"] = OmniIconName.Rows,
        ["link_off"] = OmniIconName.LinkBreak,
        ["list_alt"] = OmniIconName.Rows,
        ["lock"] = OmniIconName.Lock,
        ["lock_open"] = OmniIconName.LockOpen,
        ["lock_reset"] = OmniIconName.LockKey,
        ["login"] = OmniIconName.SignIn,
        ["logout"] = OmniIconName.SignOut,
        ["manage_search"] = OmniIconName.Search,
        ["memory"] = OmniIconName.Cpu,
        ["merge_type"] = OmniIconName.GitMerge,
        ["message"] = OmniIconName.Chat,
        ["monitor_heart"] = OmniIconName.Heartbeat,
        ["more_vert"] = OmniIconName.DotsThreeVertical,
        ["new_releases"] = OmniIconName.Sparkle,
        ["note_add"] = OmniIconName.FilePlus,
        ["notes"] = OmniIconName.TextAlignLeft,
        ["notification_important"] = OmniIconName.Bell,
        ["notifications"] = OmniIconName.Bell,
        ["notifications_active"] = OmniIconName.Bell,
        ["notifications_off"] = OmniIconName.BellSlash,
        ["open_in_new"] = OmniIconName.OpenExternal,
        ["password"] = OmniIconName.Password,
        ["pause_circle"] = OmniIconName.Pause,
        ["pending_actions"] = OmniIconName.Hourglass,
        ["people"] = OmniIconName.Users,
        ["person"] = OmniIconName.User,
        ["person_add"] = OmniIconName.UserPlus,
        ["person_search"] = OmniIconName.UserFocus,
        ["photo_library"] = OmniIconName.Image,
        ["play_arrow"] = OmniIconName.Play,
        ["play_circle"] = OmniIconName.Play,
        ["policy"] = OmniIconName.ShieldCheck,
        ["preview"] = OmniIconName.Eye,
        ["priority_high"] = OmniIconName.Warning,
        ["psychology"] = OmniIconName.Brain,
        ["publish"] = OmniIconName.Upload,
        ["queue"] = OmniIconName.Layers,
        ["receipt_long"] = OmniIconName.Document,
        ["redo"] = OmniIconName.ArrowUUpRight,
        ["refresh"] = OmniIconName.Refresh,
        ["replay"] = OmniIconName.Reset,
        ["report_problem"] = OmniIconName.Warning,
        ["restart_alt"] = OmniIconName.Refresh,
        ["resume"] = OmniIconName.Play,
        ["rocket_launch"] = OmniIconName.RocketLaunch,
        ["rule"] = OmniIconName.ListChecks,
        ["save"] = OmniIconName.Save,
        ["schedule"] = OmniIconName.Timer,
        ["science"] = OmniIconName.Flask,
        ["sd_storage"] = OmniIconName.HardDrive,
        ["search"] = OmniIconName.Search,
        ["search_off"] = OmniIconName.MagnifyingGlassMinus,
        ["security"] = OmniIconName.ShieldCheck,
        ["sell"] = OmniIconName.Tag,
        ["send"] = OmniIconName.PaperPlaneRight,
        ["sensors"] = OmniIconName.Broadcast,
        ["settings"] = OmniIconName.Settings,
        ["settings_input_antenna"] = OmniIconName.CellTower,
        ["shield"] = OmniIconName.ShieldCheck,
        ["show_chart"] = OmniIconName.ChartLine,
        ["smart_toy"] = OmniIconName.Robot,
        ["space_dashboard"] = OmniIconName.Layout,
        ["speed"] = OmniIconName.Gauge,
        ["star"] = OmniIconName.StarFilled,
        ["star_border"] = OmniIconName.Star,
        ["stop"] = OmniIconName.Stop,
        ["storage"] = OmniIconName.Database,
        ["subdirectory_arrow_right"] = OmniIconName.ArrowElbowDownRight,
        ["swap_horiz"] = OmniIconName.Swap,
        ["sync"] = OmniIconName.Sync,
        ["sync_problem"] = OmniIconName.Warning,
        ["system_security_update"] = OmniIconName.ShieldCheck,
        ["system_update"] = OmniIconName.Download,
        ["system_update_alt"] = OmniIconName.Download,
        ["tag"] = OmniIconName.Tag,
        ["target"] = OmniIconName.Target,
        ["task"] = OmniIconName.CheckCircle,
        ["task_alt"] = OmniIconName.CheckCircle,
        ["terminal"] = OmniIconName.TerminalWindow,
        ["timeline"] = OmniIconName.ChartLine,
        ["timer"] = OmniIconName.Timer,
        ["timer_off"] = OmniIconName.Pause,
        ["toggle_off"] = OmniIconName.ToggleLeft,
        ["toggle_on"] = OmniIconName.ToggleRight,
        ["touch_app"] = OmniIconName.HandTap,
        ["translate"] = OmniIconName.Globe,
        ["troubleshoot"] = OmniIconName.MagnifyingGlassPlus,
        ["tune"] = OmniIconName.Sliders,
        ["undo"] = OmniIconName.ArrowUUpLeft,
        ["update"] = OmniIconName.Sync,
        ["upload"] = OmniIconName.Upload,
        ["upload_file"] = OmniIconName.Upload,
        ["verified"] = OmniIconName.ShieldCheck,
        ["verified_user"] = OmniIconName.ShieldCheck,
        ["vertical_align_bottom"] = OmniIconName.ArrowLineDown,
        ["vertical_align_top"] = OmniIconName.ArrowLineUp,
        ["view_column"] = OmniIconName.Columns,
        ["view_list"] = OmniIconName.Rows,
        ["view_timeline"] = OmniIconName.Rows,
        ["visibility"] = OmniIconName.Eye,
        ["visibility_off"] = OmniIconName.EyeSlash,
        ["vpn_key"] = OmniIconName.Key,
        ["warning"] = OmniIconName.Warning,
        ["webhook"] = OmniIconName.Webhook,
        ["widgets"] = OmniIconName.SquaresFour,
        ["wifi"] = OmniIconName.WifiHigh,
        ["wifi_off"] = OmniIconName.WifiSlash,
        ["wifi_tethering"] = OmniIconName.Broadcast,
        ["window"] = OmniIconName.WindowsLogo,
        ["wrap_text"] = OmniIconName.ArrowElbowDownLeft,
        ["zoom_in"] = OmniIconName.MagnifyingGlassPlus,
        ["zoom_out"] = OmniIconName.MagnifyingGlassMinus,
    }.ToFrozenDictionary(StringComparer.Ordinal);

    /// <summary>Every Material name the table knows, for the tests that prove the migration is complete.</summary>
    public static IReadOnlyCollection<string> Names => Map.Keys;

    /// <summary>The Phosphor icon that replaces <paramref name="material"/>; an unknown name is a bug, not a fallback.</summary>
    public static OmniIconName Resolve(string material) =>
        Map.TryGetValue(material, out var icon)
            ? icon
            : throw new ArgumentOutOfRangeException(nameof(material), material, "Material icon name missing from MaterialIconMap.");

    /// <summary>The icon of a page header (<c>OmniPageHeader.Icon</c>) named by <paramref name="material"/>;
    /// none when the name is blank, as the former Aetheus page header drew none then.</summary>
    public static RenderFragment? HeaderIcon(string? material) => string.IsNullOrWhiteSpace(material)
        ? null
        : builder =>
        {
            builder.OpenComponent<OmniIcon>(0);
            builder.AddComponentParameter(1, nameof(OmniIcon.Name), Resolve(material));
            builder.CloseComponent();
        };
}
