# SPDX-License-Identifier: EUPL-1.2
name: application-light-template
trigger: manual
variables:
  APPLICATION_LIGHT_ADAPTER_PIPELINE: application-light-adapter

stages:
  - name: LightValidation
    group: Validation
    execution_role: build
    os: linux
    steps:
      - name: Run project-specific differential validation
        type: trigger
        pipeline: "$(APPLICATION_LIGHT_ADAPTER_PIPELINE)"
        timeout_seconds: 7200
