// SPDX-License-Identifier: EUPL-1.2
using System.Text;

namespace Aetheus.Back.Components.AgentInstaller;

public sealed class AgentInstallerService : IAgentInstallerService
{
    public AgentInstallerScript Build(string platform, string registrationToken, string serverBaseUrl, string version,
        bool pipelineRunner = true, bool serverManagement = false)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(platform);
        ArgumentException.ThrowIfNullOrWhiteSpace(registrationToken);
        ArgumentException.ThrowIfNullOrWhiteSpace(serverBaseUrl);

        // Defense-in-depth: the token is embedded literally into the generated bash/PowerShell script.
        // It is always a RandomNumberGenerator base64/base64url secret (charset below), but the builder
        // must not assume that - reject anything outside the safe charset before embedding (mirrors the
        // version regex validation, F-15), so a quote/space/metacharacter can never reach the script.
        if (!IsSafeToken(registrationToken))
            throw new BadRequestException("Invalid registration token format.");

        var trimmedUrl = serverBaseUrl.TrimEnd('/');
        var safeVersion = string.IsNullOrWhiteSpace(version) ? "dev" : version.Trim();

        return platform.ToLowerInvariant() switch
        {
            "linux" => new AgentInstallerScript(BuildBash(trimmedUrl, registrationToken, safeVersion, pipelineRunner, serverManagement), "text/x-shellscript", "aetheus-agent-install.sh"),
            "windows" => new AgentInstallerScript(BuildPowerShell(trimmedUrl, registrationToken, safeVersion, pipelineRunner), "text/plain", "aetheus-agent-install.ps1"),
            _ => throw new BadRequestException($"Unsupported platform '{platform}'. Use 'linux' or 'windows'.")
        };
    }

    // Registration tokens are base64/base64url RandomNumberGenerator secrets: letters, digits, and the
    // set + / = - _ only. No quotes, spaces, backticks, or shell/PowerShell metacharacters.
    private static bool IsSafeToken(string token) =>
        token.Length <= 512
        && token.All(c => char.IsAsciiLetterOrDigit(c) || c is '+' or '/' or '=' or '-' or '_');

    private static string BuildBash(string serverUrl, string token, string version, bool pipelineRunner, bool serverManagement)
    {
        // The one-shot wizard command DELEGATES to the canonical, hardened installer bundled in the agent
        // archive (install-agent-linux.sh), instead of re-implementing a minimal install inline. Only the
        // full installer creates the non-root agent user + locked-down systemd unit and, with
        // --module server-management, the audited sudoers drop-ins and root-owned helpers (Apache/Certbot/
        // RKHunter/...). Re-implementing a subset here silently dropped those capabilities: a wizard install
        // asking for server-management got NONE of them (it only printed a note), so a self-deploy agent
        // could not run apache/certbot steps. Delegating makes the wizard one-shot ACTUALLY provision what
        // was requested - the token/URL are validated upstream (IsSafeToken + trimmed URL).
        // Use \n explicitly - AppendLine() uses Environment.NewLine (CRLF on Windows).
        var sb = new StringBuilder();
        sb.Append("#!/usr/bin/env bash\n");
        sb.Append("# Aetheus Agent - one-shot installer (Linux)\n");
        sb.Append("# Generated by /api/agent/installer - do not check into VCS.\n");
        sb.Append("set -euo pipefail\n");
        sb.Append('\n');
        sb.Append($"SERVER_URL=\"{serverUrl}\"\n");
        sb.Append($"REGISTRATION_TOKEN=\"{token}\"\n");
        sb.Append($"AGENT_VERSION=\"{version}\"\n");
        sb.Append('\n');
        sb.Append("WORKDIR=\"$(mktemp -d)\"\n");
        sb.Append("trap 'rm -rf \"$WORKDIR\"' EXIT\n");
        sb.Append("echo \"==> Downloading agent ${AGENT_VERSION}\"\n");
        sb.Append("curl -fSL \"${SERVER_URL}/downloads/aetheus-agent-linux-x64.tar.gz\" -o \"$WORKDIR/aetheus-agent.tar.gz\"\n");
        sb.Append("tar -xzf \"$WORKDIR/aetheus-agent.tar.gz\" -C \"$WORKDIR\"\n");
        sb.Append('\n');
        // Module flags: pipeline-runner is ON by default in the installer (opt OUT with --no-pipeline-runner);
        // server-management is opt-in and grants the audited server-admin capability set.
        var moduleFlags = new StringBuilder();
        if (!pipelineRunner) moduleFlags.Append(" --no-pipeline-runner");
        if (serverManagement) moduleFlags.Append(" --module server-management");
        sb.Append("echo \"==> Installing agent via the bundled installer\"\n");
        sb.Append($"sudo sh \"$WORKDIR/install-agent-linux.sh\" --server-url \"${{SERVER_URL}}\" --token \"${{REGISTRATION_TOKEN}}\"{moduleFlags}\n");
        sb.Append('\n');
        sb.Append("echo \"==> Done - verify with: systemctl status aetheus-agent\"\n");
        return sb.ToString();
    }

    private static string BuildPowerShell(string serverUrl, string token, string version, bool pipelineRunner)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Aetheus Agent - one-shot installer (Windows)");
        sb.AppendLine("# Generated by /api/agent/installer - do not check into VCS.");
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();
        sb.AppendLine($"$ServerUrl = '{serverUrl}'");
        sb.AppendLine($"$RegistrationToken = '{token}'");
        sb.AppendLine($"$AgentVersion = '{version}'");
        sb.AppendLine("$InstallDir = 'C:\\Program Files\\AetheusAgent'");
        sb.AppendLine();
        sb.AppendLine("Write-Host \"==> Downloading agent $AgentVersion\"");
        sb.AppendLine("New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null");
        sb.AppendLine("$pkg = Join-Path $env:TEMP 'aetheus-agent.zip'");
        sb.AppendLine("Invoke-WebRequest -Uri \"$ServerUrl/downloads/aetheus-agent-win-x64.zip\" -OutFile $pkg");
        sb.AppendLine("Expand-Archive -Force -Path $pkg -DestinationPath $InstallDir");
        sb.AppendLine();
        if (pipelineRunner)
        {
            sb.AppendLine("Write-Host \"==> Pipeline-runner module: installing Git; SDKs use locked OCI images\"");
            sb.AppendLine("if (Get-Command winget -ErrorAction SilentlyContinue) {");
            sb.AppendLine("  if (-not (Get-Command git -ErrorAction SilentlyContinue)) { winget install --id Git.Git --silent --accept-package-agreements --accept-source-agreements 2>$null }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        sb.AppendLine("Write-Host \"==> Writing configuration\"");
        sb.AppendLine("$config = @{ ServerUrl = $ServerUrl; RegistrationToken = $RegistrationToken } | ConvertTo-Json");
        sb.AppendLine("Set-Content -Path (Join-Path $InstallDir 'appsettings.Production.json') -Value $config -Encoding UTF8");
        sb.AppendLine();
        sb.AppendLine("Write-Host \"==> Installing Windows service\"");
        sb.AppendLine("$exe = Join-Path $InstallDir 'Aetheus.Agent.Windows.exe'");
        sb.AppendLine("sc.exe create AetheusAgent binPath= \"$exe\" start= auto | Out-Null");
        sb.AppendLine("Start-Service AetheusAgent");
        sb.AppendLine();
        sb.AppendLine("Write-Host \"==> Done - verify with: Get-Service AetheusAgent\"");
        return sb.ToString();
    }
}
